/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package tesi.unibo;

import tesi.unibo.controller.impl.BasicController;

public class App {

    public static void main(String[] args) {
        System.out.println("ma che cazz");
        new BasicController().play();
    }
}
