/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package tesi.unibo;

import org.junit.jupiter.api.Test;
//import static org.junit.jupiter.api.Assertions.*;

public class AppTest {
    @Test void appHasAGreeting() {

    }
}
